### ISSUE TITLE
Jobs failing after AWX upgrade (ansible-runner in is out of date)

### ISSUE THREAD

**Issue by kuchynkap** [kurokobo/awx-on-k3s#91] opened 2022-06-14 14:59 UTC
Hello,

after updating to AWX-Operator 0.22.0 (AWX 21.1.0), the jobs started to fail immediately, with the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 901, in main
    res = run(**run_options)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 216, in run
    r.run()
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 130, in run
    r = ansible_runner.interface.run(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 215, in run
    r = init_runner(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 123, in init_runner
    rc = RunnerConfig(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 79, in __init__
    super(RunnerConfig, self).__init__(private_data_dir, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'suppress_env_files'

  This can be caused if the version of ansible-runner in your execution environment is out of date.

This is happening both using the default EE and freshly built custom EEs.

May I ask you for help, please?

**Comment by kurokobo** [comment] 2022-06-14 16:41
@kuchynkap 
Hi again,

The container runtime may be continuing to use an old image cached on the K3s host.

Try adding `image_pull_policy: Always` to your `awx.yaml` and run `kubectl apply -k base` again, and wait until AWX is redeployed. This will force to pull the latest image for all required images (PSQL, AWX, EE) from the Internet.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ...
  image_pull_policy: IfNotPresent     👈👈👈
```

Once the issue is resolved, you can remove the `image_pull_policy` line from your `awx.yaml` and run `kubectl apply -k base` again, to revert `imagePullPolicy` for deployment.

If the problem still occurs with images built using Ansible Builder, it is recommended to delete the old base image cached by Docker or Podman and rebuild it.

**Comment by kuchynkap** [comment] 2022-06-15 10:58
Hello,

this solved the issue! 

Many thanks!

**Comment by kurokobo** [comment] 2022-06-15 11:11
Hi, thanks for updating.

Once you have resolved the issue, I hope you will close the issue yourself next time 😃

**Closed by kurokobo** 2022-06-15 11:11 UTC
