### ISSUE TITLE
Execution environment marked as latest is not actually latest after update

### ISSUE THREAD

**Issue by amg-web** [kurokobo/awx-on-k3s#387] opened 2024-08-31 08:46 UTC
## Environment
OS: Ubuntu 22.04
Kubernetes/K3s: v1.30.4+k3s1
AWX Operator: 2.19.1

## Description
Execution environment marked as **latest** is not actually latest after update of AWX from older versions.
![Screenshot from 2024-08-31 11-43-06](https://github.com/user-attachments/assets/d8d86175-7644-4471-a445-05a0f121ecc1)
I understood this when route53 module failed with error message
> "msg": "Failed to import the required Python library (botocore and boto3) on automation-job-434-lfn5s's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"

Then I switched template to use specific version EE and all jobs were done.

with minikube I used this in kustomization.yaml, did not checked yet if it works.
```
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.12.1
  - name: quay.io/ansible/awx-ee
    newTag: latest
```

**Comment by jpmens** [comment] 2024-08-31 10:11
I don’t think this can be considered an issue attributed to this repository.

**Comment by amg-web** [comment] 2024-08-31 10:14
@jpmens 
yes. sorry.
I can not change label

**Comment by jpmens** [comment] 2024-08-31 10:16
True, but you can close the issue;)

**Comment by amg-web** [comment] 2024-08-31 10:17
What do you think about improving then close?

**Comment by jpmens** [comment] 2024-08-31 10:21
Let me clarify: I'm just an interested party and not the owner of this repository. What I intended saying is that what you describe sounds to *me* to be an AWX issue, and not one caused by the code graciously provided by @kurokobo to *install* AWX. That's all.

**Comment by amg-web** [comment] 2024-08-31 10:50
@jpmens 
**kurokobo** can change label, and may be add required lines.

**Comment by amg-web** [comment] 2024-08-31 11:09
suppose it's settings by awx itself

**Closed as not planned** 2024-08-31 11:08 UTC
Labels: bug

**Comment by kurokobo** [comment] 2024-08-31 12:49
@amg-web 
Thanks for the report, this is a known issue with AWX Operator.
I expect `latest` will not be used in the future. See the discussions on this thread for more details:
- https://github.com/ansible/awx-operator/pull/1740#discussion_r1517162486
- https://github.com/ansible/awx/issues/14969

**Comment by kurokobo** [comment] 2024-08-31 12:50
@jpmens 
Thanks as always for your comments 😃
