### ISSUE TITLE
AWX Operator upgrade from 0.25 to 0.26 fails

### ISSUE THREAD

**Issue by kuchynkap** [kurokobo/awx-on-k3s#164] opened 2022-12-20 07:34 UTC
## Environment

- OS: Ubuntu 20.04.4 LTS
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6
- AWX Operator: 0.25

## Description
Upgrade of AWX-Operator 0.25 to 0.26 fails, gets stuck forever on:
--------------------------- Ansible Task StdOut -------------------------------
TASK [installer : Stream backup from pg_dump to the new postgresql container] ***
task path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:89
------------------------------------------------------------------------------

## Step to Reproduce
Just follow the upgrade guide on https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md, persistent volume for postgres-13 created as requested.

**Comment by kurokobo** [comment] 2022-12-20 18:46
Hmm, does your password for your postgres cointains any special charactors that causes breaking shell command?
Your password will be used by following task, and there is no quotes around password, so if your password contains some special charactors like `"` shell may keep waiting forever.

https://github.com/ansible/awx-operator/blob/19c6c77c41b98bded04b3b20ace4b3fe99b682c9/roles/installer/tasks/upgrade_postgres.yml#L95-L97

There is a related issue (https://github.com/ansible/awx-operator/issues/837) but above task added after my fix.

If your password has no special charactors, more investigation is required. Could you share your output from following commands?

```bash
kubectl -n awx get awx,pod,pv,pvc
kubectl -n awx logs statefulset/awx-postgres
kubectl -n awx logs statefulset/awx-postgres-13
```

**Comment by kuchynkap** [comment] 2022-12-21 10:25
Hello,

thank you for your reply! I just checked to be sure, my password is only alphanumeric without any special characters. I found some  post on Google Groups where someone was mentioning that upgrading to 0.28 actually worked, so I was trying that today, without luck. Actually, it seems it somehow cycles through the tasks indefinitely, getting stucked on:

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Stream backup from pg_dump to the new postgresql container] ***
task path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:89

-------------------------------------------------------------------------------
{"level":"info","ts":1671618073.9435282,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/pods/awx-postgres-13-0","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"pods","Subresource":"","Name":"awx-postgres-13-0","Parts":["pods","awx-postgres-13-0"]}}

And then very quickly going through other tasks, with one actually failing:

TASK [installer : Set pg_dump command] *****************************************\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:70\nok: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set pg_restore command] **************************************\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:81\nok: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Stream backup from pg_dump to the new postgresql container] ***\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:89\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": true}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=52   changed=3    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0   \r\n\n","job":"8834408734363064390","name":"awx","namespace":"awx","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=52   changed=3    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0   


----------
{"level":"error","ts":1671618044.5843086,"msg":"Reconciler error","controller":"awx-controller","object":{"name":"awx","namespace":"awx"},"namespace":"awx","name":"awx","reconcileID":"b2554ae1-af5d-4699-98e4-adda7d52e296","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"}

Now for the output that you asked me for:

 kubectl -n awx get awx,pod,pv,pvc
NAME                      AGE
awx.awx.ansible.com/awx   478d

NAME                                                   READY   STATUS      RESTARTS   AGE
pod/awx-postgres-0                                     1/1     Running     18         189d
pod/awx-operator-controller-manager-5f65fff6fd-dnljk   2/2     Running     0          83m
pod/automation-job-984865-h5qnc                        0/1     Completed   0          82m
pod/automation-job-984845-jsvjt                        0/1     Completed   0          83m
pod/awx-postgres-13-0                                  1/1     Running     0          81m

NAME                                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS          REASON   AGE
persistentvolume/awx-projects-volume      2Gi        RWO            Retain           Bound    awx/awx-projects-claim              awx-projects-volume            478d
persistentvolume/awx-postgres-volume      2Gi        RWO            Retain           Bound    awx/postgres-awx-postgres-0         awx-postgres-volume            478d
persistentvolume/awx-backup-volume        2Gi        RWO            Retain           Bound    awx/awx-backup-claim                awx-backup-volume              298d
persistentvolume/registry-volume          5Gi        RWO            Retain           Bound    registry/registry-claim             registry-volume                292d
persistentvolume/awx-postgres-13-volume   8Gi        RWO            Retain           Bound    awx/postgres-13-awx-postgres-13-0   awx-postgres-volume            156m

NAME                                                  STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
persistentvolumeclaim/awx-projects-claim              Bound    awx-projects-volume      2Gi        RWO            awx-projects-volume   478d
persistentvolumeclaim/postgres-awx-postgres-0         Bound    awx-postgres-volume      2Gi        RWO            awx-postgres-volume   478d
persistentvolumeclaim/awx-backup-claim                Bound    awx-backup-volume        2Gi        RWO            awx-backup-volume     298d
persistentvolumeclaim/postgres-13-awx-postgres-13-0   Bound    awx-postgres-13-volume   8Gi        RWO            awx-postgres-volume   81m

 kubectl -n awx logs statefulset/awx-postgres

PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-12-20 07:11:15.468 UTC [1] LOG:  starting PostgreSQL 12.13 (Debian 12.13-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-12-20 07:11:15.469 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-12-20 07:11:15.469 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-12-20 07:11:15.475 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-12-20 07:11:15.725 UTC [27] LOG:  database system was interrupted; last known up at 2022-12-19 09:04:37 UTC
2022-12-20 07:11:17.178 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
2022-12-20 07:11:17.207 UTC [27] LOG:  redo starts at 20E/68E85BC0
2022-12-20 07:11:17.457 UTC [27] LOG:  invalid record length at 20E/6AE5AB30: wanted 24, got 0
2022-12-20 07:11:17.457 UTC [27] LOG:  redo done at 20E/6AE5AB08
2022-12-20 07:11:18.927 UTC [1] LOG:  database system is ready to accept connections
2022-12-21 08:11:00.457 UTC [203414] LOG:  could not receive data from client: Connection reset by peer

The last one is actually full of these:
kubectl -n awx logs statefulset/awx-postgres-13:

2022-12-21 10:24:45.512 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_09_pkey"
2022-12-21 10:24:45.512 UTC [369] DETAIL:  Key (id, job_created)=(10840566, 2022-11-03 09:00:18.231419+00) already exists.
2022-12-21 10:24:45.512 UTC [369] CONTEXT:  COPY main_jobevent_20221103_09, line 1
2022-12-21 10:24:45.512 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_09 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

2022-12-21 10:24:45.684 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_10_pkey"
2022-12-21 10:24:45.684 UTC [369] DETAIL:  Key (id, job_created)=(10843650, 2022-11-03 10:00:10.798315+00) already exists.
2022-12-21 10:24:45.684 UTC [369] CONTEXT:  COPY main_jobevent_20221103_10, line 1
2022-12-21 10:24:45.684 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_10 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

2022-12-21 10:24:45.856 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_11_pkey"
2022-12-21 10:24:45.856 UTC [369] DETAIL:  Key (id, job_created)=(10846734, 2022-11-03 11:00:03.380105+00) already exists.
2022-12-21 10:24:45.856 UTC [369] CONTEXT:  COPY main_jobevent_20221103_11, line 1
2022-12-21 10:24:45.856 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_11 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

2022-12-21 10:24:46.036 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_12_pkey"
2022-12-21 10:24:46.036 UTC [369] DETAIL:  Key (id, job_created)=(10849818, 2022-11-03 12:00:25.081912+00) already exists.
2022-12-21 10:24:46.036 UTC [369] CONTEXT:  COPY main_jobevent_20221103_12, line 1
2022-12-21 10:24:46.036 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_12 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

2022-12-21 10:24:46.216 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_13_pkey"
2022-12-21 10:24:46.216 UTC [369] DETAIL:  Key (id, job_created)=(10852902, 2022-11-03 13:00:19.855241+00) already exists.
2022-12-21 10:24:46.216 UTC [369] CONTEXT:  COPY main_jobevent_20221103_13, line 1
2022-12-21 10:24:46.216 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_13 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

2022-12-21 10:24:46.396 UTC [369] ERROR:  duplicate key value violates unique constraint "main_jobevent_20221103_14_pkey"
2022-12-21 10:24:46.396 UTC [369] DETAIL:  Key (id, job_created)=(10855960, 2022-11-03 14:00:17.754337+00) already exists.
2022-12-21 10:24:46.396 UTC [369] CONTEXT:  COPY main_jobevent_20221103_14, line 1
2022-12-21 10:24:46.396 UTC [369] STATEMENT:  COPY public.main_jobevent_20221103_14 (id, created, modified, event, event_data, failed, changed, host_name, play, role, task, counter, host_id, job_id, uuid, parent_uuid, end_line, playbook, start_line, stdout, verbosity, job_created) FROM stdin;

**Comment by kurokobo** [comment] 2022-12-21 20:04
@kuchynkap
Thanks for updating, so the issue seems to be on AWX side.
If you have backup of your AWX, retry upgrade by following procedure, and if your issue will have been reproduced, you should report this on AWX repository.

```bash
# Completely stop AWX Operator by removing it
kubectl -n awx delete deployment awx-operator-controller-manager

# Remove new PSQL 13
kubectl -n awx delete statefulset awx-postgres-13
kubectl -n awx delete pvc postgres-13-awx-postgres-13-0
kubectl -n awx delete pv awx-postgres-13-volume

# Remove files for new PSQL 13 and recreate it
sudo rm -rf /data/postgres-13
sudo mkdir -p /data/postgres-13
sudo chmod 755 /data/postgres-13

# Recreate PV for new PSQL 13
cat <<EOF > pv-postgres-13.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-13-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /data/postgres-13
EOF
kubectl apply -f pv-postgres-13.yaml

# Deploy new AWX Operator
git clone https://github.com/ansible/awx-operator.git -b 0.26.0
cd awx-operator
NAMESPACE=awx make deploy
```

**Comment by kuchynkap** [comment] 2022-12-22 09:22
@kurokobo 
Thank you for your help! In the beginning it looked very promising as it has not failed in early stage. But finally, it failed also:

task path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:65\nok: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set pg_dump command] *****************************************\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:70\nok: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set pg_restore command] **************************************\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:81\nok: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Stream backup from pg_dump to the new postgresql container] ***\r\ntask path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:89\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": true}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=52   changed=3    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0   \r\n\n","job":"5742676780418950479","name":"awx","namespace":"awx","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=52   changed=3    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0   


----------
{"level":"error","ts":1671699581.824264,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Reconciler error","name":"awx","namespace":"awx","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":1671699586.604346,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"1574724159804951253","EventData.Name":"installer : Check for presence of Deployment"}

Then again, it starts an infinite loop going through all the tasks. Here is an example from the logs from the postgres-13 container (although in the beginning, there were duplicate key errors like yesterday):
2022-12-22 08:59:36.366 UTC [271] ERROR:  role "tos_monitoring" does not exist
2022-12-22 08:59:36.366 UTC [271] STATEMENT:  GRANT SELECT ON TABLE public.social_auth_partial TO tos_monitoring;
2022-12-22 08:59:36.366 UTC [271] ERROR:  role "tos_monitoring" does not exist
2022-12-22 08:59:36.366 UTC [271] STATEMENT:  GRANT SELECT ON TABLE public.social_auth_usersocialauth TO tos_monitoring;
2022-12-22 08:59:36.366 UTC [271] ERROR:  role "tos_monitoring" does not exist
2022-12-22 08:59:36.366 UTC [271] STATEMENT:  GRANT SELECT ON TABLE public.sso_userenterpriseauth TO tos_monitoring;
2022-12-22 08:59:36.366 UTC [271] ERROR:  role "tos_monitoring" does not exist
2022-12-22 08:59:36.366 UTC [271] STATEMENT:  GRANT SELECT ON TABLE public.taggit_tag TO tos_monitoring;
2022-12-22 08:59:36.366 UTC [271] ERROR:  role "tos_monitoring" does not exist
2022-12-22 08:59:36.366 UTC [271] STATEMENT:  GRANT SELECT ON TABLE public.taggit_taggeditem TO tos_monitoring;

I will create an issue on the AWX repository as you mentioned.  Thank you for your time and your help!

**Comment by kuchynkap** [comment] 2022-12-22 13:49
Here is the link to that issue:
https://github.com/ansible/awx/issues/13370

**Comment by kurokobo** [comment] 2022-12-22 18:52
@kuchynkap 
Thanks for creating the issue!
F.Y.I., in GitHub you can format your code block or logs by wrapping them by ` ``` `:

Source:

````
```
# Deploy new AWX Operator
git clone https://github.com/ansible/awx-operator.git -b 0.26.0
cd awx-operator
NAMESPACE=awx
make deploy
```
````

Result:

```
# Deploy new AWX Operator
git clone https://github.com/ansible/awx-operator.git -b 0.26.0
cd awx-operator
NAMESPACE=awx
make deploy
```

This is a good way to make your report easy-to-read. Refer to https://github.github.com/gfm/ for more information about markdown syntax.

I'm closing this issue since the issue should be solved in AWX side, but feel free to open new issue if you want further assistance.

**Closed by kurokobo** 2022-12-22 18:52 UTC
