### ISSUE TITLE
Wait for Database to initialize if managed DB

### ISSUE THREAD

**Issue by ccie29824** [kurokobo/awx-on-k3s#174] opened 2023-01-12 13:39 UTC
## Environment
k3s version v1.25.4+k3s1 
Ubuntu 22.04.1 LTS
AWX Operator: 1.1.3

## Description
While deploying AWX getting below error
"Wait for Database to initialize if managed DB"

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Wait for Database to initialize if managed DB] ***************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:206

-------------------------------------------------------------------------------
{"level":"info","ts":1673530585.4271903,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1673530590.96029,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1673530596.5346725,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1673530602.0591655,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
......................
........................

**Comment by kurokobo** [comment] 2023-01-12 15:53
@ccie29824 
To ensure your PostgreSQL is up and running. Please provide following information.

```bash
kubectl -n awx get pod,pv,pvc
kubectl -n awx describe pod awx-postgres-13-0
```

In addition to above, if you have made any customization on your `awx.yaml` or other yaml files, please clarify your customization.

**Comment by ccie29824** [comment] 2023-01-12 16:51
I am using K3s with 2 worker nodes with Ubuntu as OS. K3s is customized by using MetalLb & Nginx Ingress instead of default K3s.
- AWX Hostname: awx.website.local (Not using any SSL certs)
- using default passwords - Ansible123!
![image](https://user-images.githubusercontent.com/30262889/212129657-20c5e0e1-6658-43a8-aaf0-a8bdd4f88b0b.png)

**Comment by ccie29824** [comment] 2023-01-12 17:11
![image](https://user-images.githubusercontent.com/30262889/212133975-1a4d43b1-6a1f-4461-a037-4691eb98259a.png)

**Comment by kurokobo** [comment] 2023-01-12 20:00
@ccie29824 
Thanks, I believe you can see the error about `/data/postgres-13` that has to be fixed in your screenshot.

In the first place, since you are on multi-noded cluster, you should use any _shared storage_ like NFS, iSCSI, Ceph, or GlusterFS.

I mean, the `hostPath` based PV that used in my guide can work without trouble _in single-node cluster only_, and can not work in multi-noded cluster. You can not use the PV in my guide as-is.

Refer to the Kubernetes documentation to know what PV is and what `hostPath` is.

- <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes>
- <https://kubernetes.io/docs/concepts/storage/volumes/#hostpath>

It's difficult for me to provide step-by-step guide to solve your issue since the type of PV that should be used in your cluster is highly depends on your environment.

**Comment by ccie29824** [comment] 2023-01-13 21:01
Thanks. I tried using Longhorn-based storage but not working.

**Comment by kurokobo** [comment] 2023-01-14 02:13
Hmm Longhorn should work. Maybe you're missing something.

You just said "not working" but this doesn't give any details; if your Longhorn is working properly, then the cause is completely differ from `/data/postgres-13`.
In any case, you should investigate the cause first with the `kubectl describe` command and read `Events` carefully (not just copying and pasting it here).

This is completely out-of-scope of my repo, but ensure `*_storage_class` are specified correctly.

I've never tried that but here is an example.

```yaml
spec:
  ...
  postgres_storage_class: longhorn
  postgres_storage_requirements:
    requests:
      storage: 8Gi

  projects_persistence: true
  projects_storage_class: longhorn
  projects_storage_size:  2Gi
  # Below is not required to use longhorn
  # projects_existing_claim: awx-projects-claim
  ...
```

It is important to build on small successes.
I recommend starting with a small test Pod and Longhorn to make sure Longhorn is working properly before using it with AWX.

**Closed by kurokobo** 2023-01-14 02:13 UTC
Labels: question
