### ISSUE TITLE
Deployment failed - Unable to retrieve pull secret, the image pull may not succeed - redhat-operators-pull-secret

### ISSUE THREAD

**Issue by unixsysadmin** [kurokobo/awx-on-k3s#74] opened 2022-05-13 14:35 UTC
## Environment

- OS: RHEL 8.6 
- Kubernetes/K3s: v1.23.6+k3s1
- AWX Operator: 0.21.0

## Description

Attempted to spin up AWX 21 on a brand new server using this repository with the latest operator.  The install failed with:

`May 13 13:47:19 XXX k3s[27942]: I0513 13:47:19.715551   27942 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-9nh27" secret="" err="secret \"redhat-operators-pull-secret\" not found"`

Looking in https://github.com/ansible/awx-operator/commit/859384e9f6c7136ca272a2977fc61c80c033ccdf I can see a reference to `redhat-operators-pull-secret` which was made two weeks ago but I don't recall having to configure this parameter on previous releases.

Checking the [version mapping](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/version-mapping.md#default-version-mapping-betwern-awx-operator-and-awx) table, I'm pretty sure I was able to use 0.20.1 of the operator to deploy AWX 21.0.0

| AWX Operator | AWX |
| - | - |
| 0.21.0 | 21.0.0 |
| 0.20.2 | 21.0.0 |
| 0.20.1 | 21.0.0 |

I may rebuild and test again with version 0.20.1 just to rule out a local misconfiguration.

## Step to Reproduce

1. New server install on RHEL 8.6, follow repo instructions and deploy with AWX Operator 0.21.0
2. kubectl apply -k base
3. Deployment fails with above message

**Comment by kurokobo** [comment] 2022-05-13 16:44
@unixsysadmin 
Thanks for filling the issue.

> The install failed with:
> `May 13 13:47:19 XXX k3s[27942]: I0513 13:47:19.715551 27942 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-9nh27" secret="" err="secret \"redhat-operators-pull-secret\" not found"`

I've never noticed this, but I found this error was recorded on `/var/log/messages` in my environment too.

```bash
$ sudo tail -f /var/log/messages
...
May 14 01:31:34 kuro-awx01 k3s[2268919]: I0514 01:31:34.236997 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 14 01:31:35 kuro-awx01 k3s[2268919]: I0514 01:31:35.238427 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 14 01:31:36 kuro-awx01 k3s[2268919]: I0514 01:31:36.240740 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 14 01:31:40 kuro-awx01 k3s[2268919]: I0514 01:31:40.178857 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 14 01:32:48 kuro-awx01 k3s[2268919]: I0514 01:32:48.971593 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 14 01:33:52 kuro-awx01 k3s[2268919]: I0514 01:33:52.970909 2268919 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-lk6jq" secret="" err="secret \"redhat-operators-pull-secret\" not found"
```

However, technically, an container image that published on public registry can be pulled even if the specified `imagePullSecret` is not present.

Thus, in fact, the AWX Operator deployment is successful and the pod is `Running` state in my environment. I suspect that your pod is also `Running` in your environment.

```bash
$ kubectl -n awx get all
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-operator-controller-manager-675865446d-lk6jq   2/2     Running   0          9m13s

NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.43.153.83   <none>        8443/TCP   9m13s

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           9m13s

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-675865446d   1         1         1       9m13s
```

If your pod is not in `Running` state, I guess the cause is something else. Check the `Events` of your pod by invoking `kubectl -n awx describe pod <your operator's pod name>`.

**Comment by kurokobo** [comment] 2022-05-13 16:56
Even if your pod is in `Running` state, I agree that the error message is a bit annoying. It's recorded almost every minute.

Since this is not an issue for my guide but for the AWX Operator implementation, so could you please create new issue on the AWX Operator's repo?

Just as a workaround, you can create a _dummy_ secret with name `redhat-operators-pull-secret` to suppress the error by:

```bash
kubectl -n awx create secret docker-registry redhat-operators-pull-secret \
  --docker-server=dummy.example.com \
  --docker-username=dummy \
  --docker-password=dummy
```

**Comment by kurokobo** [comment] 2022-05-14 03:36
I've modified contents of `base` directory via #75 so that secret `redhat-operators-pull-secret` is created at the same time as AWX.

The errors that are logged that you mentioned immediately after the AWX Operator is deployed, but you can ignore the errors. If you deploy AWX using the latest `base`, the errors should disappear.

**Comment by unixsysadmin** [comment] 2022-05-16 16:02
Hi @kurokobo 

Thanks again for looking at this and for making the change.

I confirm that I now only briefly see the warning about `redhat-operators-pull-secret` which happens on a clean installation when I first install the AWX Operator.

```
May 16 14:13:00 XXX k3s[26138]: I0516 14:13:00.442021   26138 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-qv8xk" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 16 14:13:29 XXX k3s[26138]: I0516 14:13:29.621409   26138 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-qv8xk" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 16 14:13:30 XXX k3s[26138]: I0516 14:13:30.624170   26138 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-qv8xk" secret="" err="secret \"redhat-operators-pull-secret\" not found"
May 16 14:13:40 XXX k3s[26138]: I0516 14:13:40.143647   26138 kubelet_pods.go:891] "Unable to retrieve pull secret, the image pull may not succeed." pod="awx/awx-operator-controller-manager-675865446d-qv8xk" secret="" err="secret \"redhat-operators-pull-secret\" not found"
```

When I subsequently run `kubectl apply -k base` the message stops appearing.

You were entirely correct - the error would not have stopped the deployment from succeeding.  I discovered that my Docker Hub credentials were incorrect and prevented a successful deployment.

I've tested again following your latest changes on a new installation and all works well.

> Since this is not an issue for my guide but for the AWX Operator implementation, so could you please create new issue on the AWX Operator's repo?

I'm happy to do this, would you be able to give me some hints as to how to phrase this - would this be correct:

> The default installation on the AWX Operator makes reference to `redhat-operators-pull-secret`.  A container image that published on public registry can be pulled even if the specified imagePullSecret is not present so the warning messages about `redhat-operators-pull-secret` being not found are not necessary.

Is the logging of the `secret not found` something that the Operator is responsible for or it that built in to K3S?

**Comment by unixsysadmin** [comment] 2022-05-18 10:34
Thanks @kurokobo - sorry it took me a little longer than expected to create this.

I have raised https://github.com/ansible/awx-operator/issues/922

**Comment by kurokobo** [comment] 2022-05-18 11:26
@unixsysadmin 
Thanks for creating new issue on that repository!

I'm closing this issue at this time. I'll update my guide once the https://github.com/ansible/awx-operator/issues/922 will be solved.

**Closed by kurokobo** 2022-05-18 11:26 UTC
